### ISSUE TITLE
Week 10

### ISSUE THREAD

**Issue by nviraj** [nviraj/era-v1#31]
**Links**

- [Material](https://canvas.instructure.com/courses/6743641/assignments/37210046?module_item_id=84640779)
- [Assignment](https://canvas.instructure.com/courses/6743641/quizzes/14793354?module_item_id=88569751)
- [Quiz](https://canvas.instructure.com/courses/6743641/quizzes/14794030?module_item_id=88574161)

**Tasks**

- [x] Download and sync course material
- [x] Add videos to playlist
- [x] Add untouched code to repo
- [x] #32 
- [x] #33 
- [ ] #34
- [x] Check script variables in notebook before final submission
- [x] Format all Notebooks
- [x] Check filenames
- [x] Check links
- [x] Check README
- [ ] Commit and merge
- [ ] Finish Assignment
- [ ] Go through course material
- [ ] Finish Quiz
- [ ] Add previous solution files to repo
